### ISSUE TITLE
error while importing in android studio

### ISSUE THREAD

**Issue by Shailesh7779** [kinecosystem/kin-core-android#2]
Error:(78, 1) Could not get unknown property 'cleanRPC' for project ':kin-sdk-core' of type org.gradle.api.Project.

**Comment by yosriz** [comment]
@Shailesh7779 , the project is in its early phases, and many crucial changes done recently,
please clone the repo again

**Comment by Shailesh7779** [comment]
Error:Execution failed for task ':kin-sdk-core:prepareRPC'.
> A problem occurred starting process 'command 'make''

**Comment by bogdantmm92** [comment]
I have the same problem when trying to use it.
Unable to resolve dependency for ':kin-core@debug/compileClasspath': Could not resolve project :android-stellar-sdk.
