### ISSUE TITLE
Importing kin accounts

### ISSUE THREAD

**Issue by adevezin** [kinecosystem/kin-core-android#29]
I see there is code to create new kin accounts. But i do not see code anywhere to import an existing kin account

**Comment by yosriz** [comment]
we are considering import/export scenarios and all of its implications, currently, there is no plan to add this functionality

**Comment by adevezin** [comment]
@yosriz Without this functionality it will be extremely hard to create useful application for users. They will have to transfer any balances to a new application everytime
